export const data = [{
    "id": 1,
    "Title": "Mr",
    "Description": "ÅÍÎÏ˝ÓÔÒÚÆ☃",
    "Author": "Ruttger",
    "Difficulty": "easy"
  }, {
    "id": 2,
    "Title": "Dr",
    "Description": "​",
    "Author": "Fiorenze",
    "Difficulty": "medium"
  }, {
    "id": 3,
    "Title": "Rev",
    "Description": "ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ",
    "Author": "Debora",
    "Difficulty": "hard"
  }, {
    "id": 4,
    "Title": "Ms",
    "Description": "\"\"",
    "Author": "Jackie",
    "Difficulty": "medium"
  }, {
    "id": 5,
    "Title": "Honorable",
    "Description": "パーティーへ行かないか",
    "Author": "Alwyn",
    "Difficulty": "hard"
  }, {
    "id": 6,
    "Title": "Mrs",
    "Description": "¡™£¢∞§¶•ªº–≠",
    "Author": "Delcina",
    "Difficulty": "Valery"
  }, {
    "id": 7,
    "Title": "Honorable",
    "Description": "!@#$%^&*()",
    "Author": "Robinet",
    "Difficulty": "Lynsey"
  }, {
    "id": 8,
    "Title": "Mr",
    "Description": "\"",
    "Author": "Forbes",
    "Difficulty": "Adria"
  }, {
    "id": 9,
    "Title": "Dr",
    "Description": " ",
    "Author": "Cynde",
    "Difficulty": "Guido"
  }, {
    "id": 10,
    "Title": "Dr",
    "Description": "␢",
    "Author": "Harlen",
    "Difficulty": "Anastasie"
  }, {
    "id": 11,
    "Title": "Honorable",
    "Description": "・(￣∀￣)・:*:",
    "Author": "Colman",
    "Difficulty": "Issiah"
  }, {
    "id": 12,
    "Title": "Mr",
    "Description": "NULL",
    "Author": "Teodor",
    "Difficulty": "Ronnie"
  }, {
    "id": 13,
    "Title": "Ms",
    "Description": "̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕",
    "Author": "Marissa",
    "Difficulty": "Karol"
  }, {
    "id": 14,
    "Title": "Mrs",
    "Description": "() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }",
    "Author": "Kincaid",
    "Difficulty": "Rosita"
  }, {
    "id": 15,
    "Title": "Dr",
    "Description": "‫test‫",
    "Author": "Eba",
    "Difficulty": "Josey"
  }, {
    "id": 16,
    "Title": "Dr",
    "Description": "1",
    "Author": "Carr",
    "Difficulty": "Diena"
  }, {
    "id": 17,
    "Title": "Ms",
    "Description": "‫test‫",
    "Author": "Bart",
    "Difficulty": "Shaun"
  }, {
    "id": 18,
    "Title": "Rev",
    "Description": "᠎",
    "Author": "Deloris",
    "Difficulty": "Cassandry"
  }, {
    "id": 19,
    "Title": "Mr",
    "Description": "'",
    "Author": "Kareem",
    "Difficulty": "Janelle"
  }, {
    "id": 20,
    "Title": "Dr",
    "Description": "1.00",
    "Author": "Dorisa",
    "Difficulty": "Pammie"
  }]